media:
  name: images
  label: Images
  input: src/images/services
  output: /images/services
  path: "."
  extensions: [png, jpg, jpeg, webp, svg]

settings:
  content:
    merge: true

content:
  - name: services
    label: Services
    type: collection
    path: src/content/services

    view:
      primary: title
      fields: [title, sortOrder, image, price, category, featured, tags]
      sort: [sortOrder, title]

    fields:
      - { name: title, label: Title, type: string }
      - { name: slug, label: URL Slug, type: string }
      - { name: description, label: Description, type: text }
      - {
          name: sortOrder,
          label: Display Order,
          type: number,
          description: "Lower numbers appear first (1, 2, 3...)",
        }
      - { name: price, label: Price, type: number }

      - name: image
        label: Image
        type: image
        options: { media: images, path: . }

      - name: tags
        label: Tags
        type: string
        list: true

      - { name: featured, label: Featured, type: boolean }
      - { name: category, label: Category, type: string }

      # New fields for richer content
      - { name: intro, label: Intro, type: text }
      - name: benefits
        label: Benefits
        type: string
        list: true
      - name: specialties
        label: Specialties
        type: string
        list: true

      # Features (list of objects)
      - name: features
        label: Features
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}"
        fields:
          - { name: title, label: Feature Title, type: string }
          - { name: description, label: Feature Description, type: text }

      # Process steps (list of objects)
      - name: process
        label: Process Steps
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}"
        fields:
          - { name: title, label: Step Title, type: string }
          - { name: description, label: Step Description, type: text }

      # FAQs (list of objects)
      - name: faqs
        label: FAQs
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.question}"
        fields:
          - { name: question, label: Question, type: string }
          - { name: answer, label: Answer, type: text }

  - name: legal
    label: Legal Pages
    type: collection
    path: src/content/legal

    view:
      primary: page
      fields: [page, title, dateModified]
      sort: [page]

    fields:
      - { name: page, label: Page Name, type: string }
      - { name: pubDate, label: Publish Date, type: datetime }
      - { name: title, label: Page Title, type: string }
      - { name: description, label: Description, type: text }
      - { name: keywords, label: Keywords, type: string }
      - { name: author, label: Author, type: string }
      - { name: datePublished, label: Date Published, type: datetime }
      - { name: dateModified, label: Date Modified, type: datetime }
            - { name: content, label: Content, type: text }
