media:
  name: images
  label: Images
  input: src/images/services
  output: /images/services
  path: "."
  extensions: [png, jpg, jpeg, webp, svg]

settings:
  content:
    merge: true

content:
  - name: services
    label: Services
    type: collection
    path: src/content/services
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: text }
      - { name: price, label: Price, type: number }

      - name: image
        label: Image
        type: image
        options:
          media: images
          path: .

      # Tags MUST be a list of strings (not a textarea)
      - name: tags
        label: Tags
        type: list
        field:
          name: tag
          label: Tag
          type: string

      - { name: featured, label: Featured, type: boolean }
      - { name: category, label: Category, type: string }

      # Features = list of objects; show the title in the UI
      - name: features
        label: Features
        type: list
        displayField: title
        fields:
          - { name: title, label: Feature Title, type: string }
          - { name: description, label: Feature Description, type: text }

      # Steps = list of objects; show the title in the UI
      - name: steps
        label: Steps
        type: list
        displayField: title
        fields:
          - { name: title, label: Step Title, type: string }
          - { name: description, label: Step Description, type: text }

      # FAQs = list of objects; show the question in the UI
      - name: questions
        label: FAQs
        type: list
        displayField: question
        fields:
          - { name: question, label: Question, type: string }
          - { name: answer, label: Answer, type: text }
