media:
  name: images
  label: Images
  input: src/images/services
  output: /images/services
  path: "."
  extensions: [png, jpg, jpeg, webp, svg]

settings:
  content:
    merge: true

content:
  - name: services
    label: Services
    type: collection
    path: src/content/services

    view:
      primary: title
      fields: [title, image, price, category, featured, tags]
      sort: [title]

    fields:
      - { name: title, label: Title, type: string }
      - { name: slug, label: URL Slug, type: string }
      - { name: price, label: Price, type: number }

      - name: image
        label: Image
        type: image
        options: { media: images, path: . }

      - name: tags
        label: Tags
        type: string
        list: true

      - { name: featured, label: Featured, type: boolean }
      - { name: category, label: Category, type: string }

      # New fields for richer content
      - { name: intro, label: Intro, type: text }
      - name: benefits
        label: Benefits
        type: string
        list: true
      - name: specialties
        label: Specialties
        type: string
        list: true

      # Features (list of objects)
      - name: features
        label: Features
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}"
        fields:
          - { name: title, label: Feature Title, type: string }
          - { name: description, label: Feature Description, type: text }

      # Process steps (list of objects)
      - name: process
        label: Process Steps
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}"
        fields:
          - { name: title, label: Step Title, type: string }
          - { name: description, label: Step Description, type: text }

      # FAQs (list of objects)
      - name: faqs
        label: FAQs
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.question}"
        fields:
          - { name: question, label: Question, type: string }
          - { name: answer, label: Answer, type: text }
